apiVersion: apps/v1
kind: Deployment
metadata:
  name: unit8-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: unit8
  replicas: 1 
  template:
    metadata:
      labels:
        app: unit8
    spec:
      containers:
      - name: unit8
        image: devilke/unit8:test
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: unit8-service
  namespace: default
  labels:
    app: unit8
spec:
  ports:
  - name: http
    port: 80
    targetPort: 5000
  selector:
    app: unit8