name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
 main:
   runs-on: ubuntu-latest
   steps:
     -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
     -
       name: Login to DockerHub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: devilke/unit8:test
     -
      name: Kubernetes CLI - kubectl
      # You may pin to the exact commit or the version.
      # uses: steebchen/kubectl@8d86812f13f42dbc67dd0ffd787cde5e1833f789
      uses: steebchen/kubectl@v1.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}
        args: set image --record deployment/my-app container=devilke/unit8:test
          
